import Head from "next/head";
import Image from "next/image";
import Nav from "../components/Nav";
// import Head from "next/head";
import HomeProducts from "../components/HomeProducts";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Apple Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="icon"
          href="https://upload.wikimedia.org/wikipedia/commons/8/84/Apple_Computer_Logo_rainbow.svg"
        />
      </Head>
      <Nav />
      <HomeProducts />
    </div>
  );
}
